-- Adds Level 3 to the curated question bank: 20 logic + 20 riddle + 20
-- spatial questions, matching the "at least 20 per (level, category)
-- bucket" standard this repo holds itself to. Every answer below has
-- been worked through by hand and checked against the existing bank for
-- exact-text and same-riddle-different-wording duplicates before being
-- added (see docs/blueprint.md).

-- ---------------------------------------------------------------------------
-- Level 3 Logic (20 new)
-- ---------------------------------------------------------------------------
insert into questions (level, category, question_text, options, correct_option_index, explanation) values
(3, 'logic', 'Four friends - Dev, Priya, Raj, and Sana - are ranked 1st to 4th in a race. Dev finished right after Priya. Raj finished before Priya. Sana finished last. Who finished first?', '["Raj","Priya","Dev","Sana"]', 0, 'Raj finished before Priya, and Dev finished right after Priya, so the order is Raj, Priya, Dev, then Sana last - Raj is first.'),
(3, 'logic', 'A bag has 4 red balls and 6 blue balls. If you pick one ball without looking, what is the probability it is red?', '["2/5","1/2","3/5","1/4"]', 0, '4 red out of 10 total balls = 4/10, which simplifies to 2/5.'),
(3, 'logic', 'All Woggles are Zibbits. No Zibbits are Plunk. Is it possible for a Woggle to be a Plunk?', '["Yes, always","No, never","Only sometimes","Cannot be determined"]', 1, 'Every Woggle is a Zibbit, and no Zibbit is a Plunk, so no Woggle can possibly be a Plunk.'),
(3, 'logic', 'If today is Tuesday, what day of the week will it be in 100 days?', '["Wednesday","Thursday","Friday","Saturday"]', 1, '100 divided by 7 leaves a remainder of 2, so 100 days from Tuesday lands 2 days later: Thursday.'),
(3, 'logic', 'A store sells notebooks for $3 each, with a deal: buy 2, get 1 free. How much do 6 notebooks cost under this deal?', '["$12","$15","$18","$9"]', 0, 'With buy-2-get-1-free, every 3 notebooks only costs 2. For 6 notebooks (two groups of 3), you pay for 4: 4 x $3 = $12.'),
(3, 'logic', 'In a class of 30 students, 18 like math and 15 like science. 8 students like both. How many students like neither?', '["5","8","10","7"]', 0, '18 + 15 - 8 = 25 students like at least one subject (the 8 who like both are not double-counted). 30 - 25 = 5 like neither.'),
(3, 'logic', 'A cipher shifts every letter forward by 2 (A to C, B to D, and so on). The word ICOG was encoded this way. What is the original word?', '["GAME","GATE","CODE","GAZE"]', 0, 'Shifting each letter of ICOG back by 2: I to G, C to A, O to M, G to E, giving GAME.'),
(3, 'logic', 'Ravi is twice as old as his sister Meera. In 5 years, Ravi will be 25. How old is Meera right now?', '["10","15","8","12"]', 0, 'In 5 years Ravi will be 25, so Ravi is 20 now. Since Ravi is twice Meera''s age, Meera is 20 / 2 = 10.'),
(3, 'logic', 'Three boxes are labeled Apples, Oranges, and Mixed - but all three labels are wrong. You may pick one fruit from one box to figure out the true contents of all three. Which box should you pick from?', '["Apples","Oranges","Mixed","Any box works"]', 2, 'Since every label is wrong, the box labeled Mixed cannot actually be mixed - it must be all one fruit. Picking from it reveals the truth, and from there the wrong labels on the other two boxes give themselves away.'),
(3, 'logic', 'A frog is at the bottom of a 10-meter well. Each day it climbs up 3 meters, but each night it slides back 2 meters. On which day does it first reach the top?', '["Day 7","Day 8","Day 9","Day 10"]', 1, 'Each full day-night cycle gains 1 meter net (climb 3, slide back 2). After 7 nights the frog is at 7m; on day 8 it climbs from 7m to 10m and reaches the top before sliding back.'),
(3, 'logic', 'Five houses stand in a row, numbered 1 to 5 left to right. The red house is house 1. The blue house is house 3. The green house is immediately left of the blue house. Which house is green?', '["House 1","House 2","House 4","House 5"]', 1, 'The blue house is house 3, and green is immediately to its left, so green is house 2.'),
(3, 'logic', 'If all Krobs are Flurbs, and some Flurbs are Nix, can we be sure that some Krobs are Nix?', '["Yes, definitely","No, cannot be sure","No, definitely not","Only if all Flurbs are Nix"]', 1, 'All Krobs are Flurbs, but only SOME Flurbs are Nix - there is no guarantee any Krob falls into that some, so we cannot be sure.'),
(3, 'logic', 'At 4:00 on a standard clock, what is the angle between the hour hand and the minute hand?', '["90 degrees","100 degrees","120 degrees","150 degrees"]', 2, 'At 4:00 the minute hand points at 12 (0 degrees) and the hour hand points at the 4 (4 x 30 degrees = 120 degrees), so the angle between them is 120 degrees.'),
(3, 'logic', 'In a race, Arjun beats Priya, and Priya beats Kabir. If the race had no ties, who definitely finished last among these three?', '["Arjun","Priya","Kabir","Cannot tell"]', 2, 'Arjun finished ahead of Priya, and Priya finished ahead of Kabir, so the order is Arjun, then Priya, then Kabir - Kabir is last.'),
(3, 'logic', 'A jar has only red and green marbles. There are 3 times as many red marbles as green. If there are 8 green marbles, how many marbles are in the jar in total?', '["24","32","28","20"]', 1, 'Red marbles = 3 x 8 = 24. Total = 24 red + 8 green = 32.'),
(3, 'logic', 'What is the next number in this sequence: 2, 6, 12, 20, 30, ___?', '["40","42","36","44"]', 1, 'The differences between terms increase by 2 each time (4, 6, 8, 10, then 12), so the next term is 30 + 12 = 42.'),
(3, 'logic', 'Two friends, Alex and Sam, are either always truthful or always lying. Alex says, Sam always lies. Sam says, Alex and I are both truthful. Who is telling the truth?', '["Only Alex","Only Sam","Both","Neither"]', 0, 'If Alex is truthful, Sam must always lie (per Alex''s statement) - and Sam''s claim that both are truthful would then be false, which fits a liar. The other case leads to a contradiction, so Alex is truthful and Sam lies.'),
(3, 'logic', 'A rope burns unevenly but takes exactly 60 minutes to burn completely from one end. If you light both ends at once, how long until the rope is completely burnt?', '["15 minutes","30 minutes","45 minutes","60 minutes"]', 1, 'Even though the rope burns unevenly, lighting both ends means the two flames together consume the same total rope in half the time - 30 minutes.'),
(3, 'logic', 'A number is chosen at random from 1 to 20. What is the probability that it is divisible by 3?', '["3/10","1/3","1/4","2/5"]', 0, 'There are 6 multiples of 3 between 1 and 20 (3, 6, 9, 12, 15, 18), so the probability is 6/20 = 3/10.'),
(3, 'logic', 'Sonia, Tanvi, and Uday each play exactly one sport: chess, tennis, or swimming, with no two playing the same sport. Sonia does not play tennis. Uday does not play chess or tennis. What sport does Uday play?', '["Chess","Tennis","Swimming","Cannot tell"]', 2, 'Since Uday plays neither chess nor tennis, and each person plays exactly one of the three sports, Uday must play swimming.');

-- ---------------------------------------------------------------------------
-- Level 3 Riddle (20 new)
-- ---------------------------------------------------------------------------
insert into questions (level, category, question_text, options, correct_option_index, explanation) values
(3, 'riddle', 'I am taken from a mine, and shut up in a wooden case, from which I am never released, and yet I am used by almost everyone. What am I?', '["Pencil lead","A nail","A key","A battery"]', 0, 'Pencil lead (graphite) is mined, then sealed inside a wooden pencil case - it is never removed from the wood, yet almost everyone uses it to write.'),
(3, 'riddle', 'I am not alive, but I grow. I do not have lungs, but I need air. I do not have a mouth, but water kills me. What am I?', '["Fire","A plant","A crystal","A shadow"]', 0, 'Fire spreads (grows), needs oxygen to keep burning, and is put out by water.'),
(3, 'riddle', 'What kind of cup does not hold any water at all?', '["A cupcake","A teacup","A buttercup","A measuring cup"]', 0, 'The word cupcake contains cup but is a baked treat - it cannot hold water at all.'),
(3, 'riddle', 'What can you hold without ever touching it, and lose forever the moment you say it out loud to someone else?', '["A secret","A promise","A whisper","A wish"]', 0, 'A secret is something you can hold in your mind with no physical object at all, and it stops being a secret the moment you share it.'),
(3, 'riddle', 'What word becomes shorter when you add two letters to it?', '["Short","Long","Big","Tiny"]', 0, 'Adding er to the word short spells shorter - the word itself becomes the word shorter.'),
(3, 'riddle', 'I have branches, but no fruit, trunk, or leaves. What am I?', '["A bank","A tree","A river","A library"]', 0, 'A bank has branches (different locations) but none of the parts a real tree has.'),
(3, 'riddle', 'What English word refers to all 26 letters, yet the word itself has only three syllables?', '["Alphabet","Dictionary","Vocabulary","Language"]', 0, 'The word alphabet refers to all 26 letters, while the word itself has only three syllables: al-pha-bet.'),
(3, 'riddle', 'What kind of ship has no captain, no crew, and never once sails on water?', '["A relationship","A paper ship","A ghost ship","A toy ship"]', 0, 'The word relationship ends in ship, playing on the word - but it has no captain, no crew, and nothing to do with water.'),
(3, 'riddle', 'What begins with T, ends with T, and has T in it?', '["A teapot","A toast","A trumpet","A ticket"]', 0, 'Teapot begins with T, ends with T, and has a T right in the middle too.'),
(3, 'riddle', 'What gets bigger every time you share it with someone else, yet never actually runs out?', '["Knowledge","Money","Time","Food"]', 0, 'Sharing knowledge with someone does not use it up - teaching it to others often deepens your own understanding too.'),
(3, 'riddle', 'What runs all day without legs and can be found humming quietly in your kitchen?', '["A refrigerator","A clock","A faucet","A fan"]', 0, 'A refrigerator runs constantly (operates) without having any legs, and hums quietly while keeping food cold in the kitchen.'),
(3, 'riddle', 'What kind of tree can you carry in your hand?', '["A palm tree","An oak tree","A fir tree","A willow tree"]', 0, 'It is a play on words - a palm tree shares its name with the palm of your hand, which you can obviously carry.'),
(3, 'riddle', 'What kind of table has no legs at all?', '["A multiplication table","A dinner table","A picnic table","A coffee table"]', 0, 'A multiplication table is just a grid of numbers - it has no physical legs like a piece of furniture would.'),
(3, 'riddle', 'What comes once in a minute, twice in a moment, but never in a thousand years?', '["The letter M","The letter O","The number 1","The word now"]', 0, 'The letter M appears once in minute, twice in moment, but not at all in thousand years.'),
(3, 'riddle', 'What do you experience every night with your eyes closed, that feels completely real until you wake up?', '["A dream","A memory","A thought","A wish"]', 0, 'A dream happens while you sleep with your eyes closed, and often feels completely real - until you wake up and realize it was not.'),
(3, 'riddle', 'What kind of coat is always wet when you put it on?', '["A coat of paint","A raincoat","A fur coat","A coat of ice"]', 0, 'Freshly applied paint - a coat of paint - is always wet right when it goes on.'),
(3, 'riddle', 'What kind of nut has no shell at all?', '["A doughnut","A peanut","A walnut","A coconut"]', 0, 'A doughnut has the word nut right in its name, but it is a fried pastry with no shell at all.'),
(3, 'riddle', 'What English word keeps the same pronunciation even after you take away four of its five letters?', '["Queue","Eight","Bread","Knight"]', 0, 'Queue is pronounced just like the single letter Q - so even after removing four of its five letters, it still sounds the same.'),
(3, 'riddle', 'A man looks at a portrait and says: Brothers and sisters, I have none. But this man''s father is my father''s son. Whose picture is he looking at?', '["His own son","His father","His brother","Himself"]', 0, 'Since he has no siblings, my father''s son can only be himself. So this man''s father is me - meaning the man in the picture is his own son.'),
(3, 'riddle', 'What has many rings but no fingers, and can tell you how old a tree is?', '["A tree trunk","A phone","An onion","A target"]', 0, 'The rings inside a tree trunk''s cross-section each represent one year of growth, letting you count a tree''s age.');

-- ---------------------------------------------------------------------------
-- Level 3 Spatial (20 new)
-- ---------------------------------------------------------------------------
insert into questions (level, category, question_text, options, correct_option_index, explanation) values
(3, 'spatial', 'A cube is painted red on all faces, then cut into 27 smaller equal cubes (3x3x3). How many of the small cubes have exactly 2 red faces?', '["8","12","6","1"]', 1, 'In a 3x3x3 cube, the small cubes with exactly 2 painted faces are the ones along each edge (excluding corners) - there are 12 edges, each contributing exactly 1 such cube.'),
(3, 'spatial', 'How many faces does a triangular prism have?', '["4","5","6","8"]', 1, 'A triangular prism has 2 triangular faces (top and bottom) and 3 rectangular side faces, for 5 faces total.'),
(3, 'spatial', 'If you fold a net made of 6 equal squares arranged in a cross (plus) shape, what 3D shape do you get?', '["A cube","A pyramid","A cylinder","A prism"]', 0, 'A cross-shaped net of 6 squares folds up into a cube - each square becomes one face.'),
(3, 'spatial', 'You are facing East. You turn 90 degrees clockwise, then 180 degrees, then 90 degrees counter-clockwise. Which direction do you now face?', '["North","South","East","West"]', 3, 'Starting at East: turning 90 degrees clockwise faces South; turning 180 degrees faces North; turning 90 degrees counter-clockwise from North faces West.'),
(3, 'spatial', 'A rectangular box is 4 cm long, 3 cm wide, and 2 cm tall. What is its volume?', '["24 cubic cm","9 cubic cm","18 cubic cm","48 cubic cm"]', 0, 'Volume of a rectangular box = length x width x height = 4 x 3 x 2 = 24 cubic cm.'),
(3, 'spatial', 'How many lines of symmetry does a regular pentagon have?', '["3","4","5","10"]', 2, 'A regular pentagon has 5 lines of symmetry - one through each vertex and the midpoint of the opposite side.'),
(3, 'spatial', 'If you look at the letter B in a vertical mirror held to its right, what do you see?', '["A backwards B (mirror image)","The letter D","The letter P","The letter R"]', 0, 'A vertical mirror flips the letter left-to-right, producing a mirror image of B - it does not turn into a different real letter.'),
(3, 'spatial', 'A square paper is folded in half twice, so it becomes a smaller square. If you cut a small triangle off one corner (not touching any fold line) and then unfold it completely, how many holes are there?', '["1","2","4","8"]', 2, 'Folding the square in half twice stacks the paper into 4 layers. A cut through a corner not on a fold line goes through all 4 layers, creating 4 separate holes once unfolded.'),
(3, 'spatial', 'A ladder 13 meters long leans against a wall. The bottom of the ladder is 5 meters from the wall. How high up the wall does the ladder reach?', '["12 meters","10 meters","8 meters","14 meters"]', 0, 'This is a 5-12-13 right triangle: 5 squared + 12 squared = 25 + 144 = 169 = 13 squared, so the ladder reaches 12 meters up the wall.'),
(3, 'spatial', 'How many edges does a square pyramid have (a pyramid with a square base)?', '["4","6","8","10"]', 2, 'A square pyramid has 4 edges around its square base plus 4 edges running up to the apex, for 8 edges total.'),
(3, 'spatial', 'If you unfold (flatten) a cylinder''s curved side into a flat shape, what shape do you get?', '["A rectangle","A triangle","A circle","A trapezoid"]', 0, 'The curved surface of a cylinder unrolls flat into a rectangle, with the circles remaining as the top and bottom.'),
(3, 'spatial', 'Two mirrors are placed at a right angle (90 degrees) to each other. If you look into the corner where they meet, how many reflections of yourself can you typically see?', '["1","2","3","4"]', 2, 'Two mirrors at a right angle produce three reflections: one in each mirror individually, plus one double reflection from light bouncing off both mirrors.'),
(3, 'spatial', 'A regular hexagon is cut in half through its center, from the midpoint of one flat side to the midpoint of the opposite flat side. What shape is each half?', '["A trapezoid","A triangle","A rectangle","A pentagon"]', 0, 'Slicing a regular hexagon between the midpoints of two opposite sides produces two identical trapezoid-shaped halves.'),
(3, 'spatial', 'A treasure map says: start at the flag, walk 3 steps North, then 4 steps East, then dig. If you instead walked directly from the flag to the treasure in a straight line, how many steps would that be?', '["5 steps","7 steps","6 steps","4 steps"]', 0, 'Walking 3 steps North and 4 steps East forms a right triangle with legs 3 and 4; the direct straight-line distance is the hypotenuse: the square root of (3 squared + 4 squared) = 5 steps.'),
(3, 'spatial', 'How many vertices (corners) does a regular octahedron have?', '["6","8","10","12"]', 0, 'A regular octahedron (8 triangular faces) has 6 vertices - like two pyramids joined at their square bases.'),
(3, 'spatial', 'If you fold a strip of paper into a loop with a half-twist before joining the ends (a Mobius strip) and draw a line down the middle all the way around, how many sides does the strip actually have?', '["1","2","3","0"]', 0, 'A Mobius strip''s half-twist means it only has one continuous side and one continuous edge - the line drawn down the middle eventually meets back up with itself on both sides.'),
(3, 'spatial', 'A rectangular garden is 12 meters by 8 meters. A square patio with 4-meter sides sits inside it. What is the area of the garden NOT covered by the patio?', '["80 sq m","84 sq m","76 sq m","88 sq m"]', 0, 'Garden area = 12 x 8 = 96 sq m. Patio area = 4 x 4 = 16 sq m. Remaining = 96 - 16 = 80 sq m.'),
(3, 'spatial', 'At what time do the hour and minute hands of a clock point in exactly opposite directions (180 degrees apart), right around 6 o''clock?', '["6:00","6:30","5:30","6:15"]', 0, 'At exactly 6:00, the minute hand points to 12 and the hour hand points to 6 - directly opposite each other, 180 degrees apart.'),
(3, 'spatial', 'A cube''s edge length is doubled. By what factor does its volume increase?', '["2 times","4 times","6 times","8 times"]', 3, 'Volume = edge cubed, so doubling the edge length multiplies the volume by 2 cubed = 8.'),
(3, 'spatial', 'If you walk 10 steps North, then 10 steps East, then 10 steps South, then 10 steps West, where do you end up compared to where you started?', '["Back at the start","10 steps North of start","10 steps East of start","20 steps away from start"]', 0, 'Walking North then East then South then West, each for the same distance, traces a square path that returns exactly to the starting point.');
